### ISSUE TITLE
hi，朋友，我有些地方不太明白，能否支持如下所述使用方式？

### ISSUE THREAD

**Issue by sanguohot** [ihciah/go-shadowsocks-magic#2]
`原ss客户端<--->magic客户端<---（自定义多路和可配置混淆算法）---->magic服务器<--->原ss服务器`
这样可以便于利用原ss客户端的pac以及原ss服务端的ssmgr流量管理功能，界面也友善
并且源ss客户端监听的1080是经过privoxy转了一道，可以直接支持http/https代理

**Comment by ihciah** [comment]
I think it meaningless.
The shadowsocks is designed to avoid pattern. If there's another protocol over the ss protocol, the pattern of new protocol will be recongized, or there's no need to use ss protocol.
The magic protocol is under the ss protocol.

I'm considering modify shadowsocks-windows client, but since I'm not fimiliar with C# development, it may cost some time.

**Comment by ihciah** [comment]
Also, you can use kcp if your ISP doesn't drop your UDP packets. The kcp itself can transmit data in parallel.
